language: java
dist: trusty
sudo: false

notifications:
  email: false

jdk:
- oraclejdk8

addons:
  sonarcloud:
    organization: "omkar9999-github"

before_script: cd Extended-Spring-Batch

script: mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
